# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-28 09:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='subtitle',
            field=models.CharField(default='cameron', max_length=20),
            preserve_default=False,
        ),
    ]
